project_id = "xispoxjjjaevbxstrepr"

[functions.paint]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.submit-wire-order]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
